### ISSUE TITLE
(Dev) Dependencies?

### ISSUE THREAD

**Issue by carstenjaksch** [huntabyte/formsnap#101]
Your quick start guide tells me to install all packages as a dependency:

```bash
npm install formsnap sveltekit-superforms zod
```

But Superforms tells me to install as **dev** dependency:

```bash
npm i -D sveltekit-superforms zod
```

I feel like installing all these packages as normal dependencies and shipping them to production makes the site performance very worse. Do we actually need to install them this way?

**Comment by huntabyte** [comment]
When using SvelteKit/Vite, it doesn't matter anymore: https://github.com/vitejs/vite/discussions/1803#discussioncomment-322107
