### ISSUE TITLE
Support SvelteKit 2.0

### ISSUE THREAD

**Issue by carstenjaksch** [huntabyte/formsnap#105]
My form does not work after upgrading to SvelteKit 2. Since Superforms lists SvelteKit 2 as a peer dependency and Formsnap does not, I assume that SvelteKit 2 is currently not supported by Formsnap?

Related discussion: https://github.com/ciscoheat/sveltekit-superforms/discussions/302

**Comment by carstenjaksch** [comment]
In addition to the docs change, I suggest to add SvelteKit (2) as `peerDependency` in **package.json**, like Superforms:

```json
"@sveltejs/kit": "1.x || 2.x",
```

This makes it clear what SvelteKit versions are supported.

**Comment by AdrianGonz97** [comment]
Hey @carstenjaksch, as we don't depend on SvelteKit, it would be unnecessary to add it as a peer dependency. Would you mind providing a reproduction demonstrating this issue?
