### ISSUE TITLE
Optimize bundle size in production

### ISSUE THREAD

**Issue by carstenjaksch** [huntabyte/formsnap#108]
I use `rollup-plugin-visualizer` to analyze the production bundle and I noticed that Formsnap always imports SuperDebug.

Is there a way to import it only if `debug={true}` is used?

Here are some words about selective importing: https://kit.svelte.dev/docs/performance#reducing-code-size-selective-loading

Never used it myself, but if that's a thing, that would make the bundle size a bit smaller.

This is how the visualized bundle of my ContactForm component looks:

<img width="483" alt="Bildschirm­foto 2023-12-28 um 11 19 43" src="https://github.com/huntabyte/formsnap/assets/82714642/5bb0902d-9221-47cd-b78a-09eed3741267">

I wonder if there is a way to reduce the Zod bundle too. The client side validation seems to f*ck with the performance scores (Vercel Speed Insights, Pagespeed Insights, etc).

**Comment by huntabyte** [comment]
Zod is always going to drag it down due to its inability to tree-shake. Superforms v2 will introduce support for alternate validation libraries like [Valibot](https://valibot.dev/), which are much more lightweight.

I'll look into the selective importing of the `SuperDebug` component!
