### ISSUE TITLE
Accessibility on FormControl component

### ISSUE THREAD

**Issue by arcuo** [huntabyte/formsnap#109]
The control component seems to add an `input`.

Accessibility-wise this input causes two issues:

- When you tab, it is focused. Should add `tabindex='-1'
- When you hover the area, the the pointer events are still shown as `pointerEvents` is set instead of `pointer-events`. This seems to be a general problem with the `hiddenInputStyle` string. Either, should add some "camelToSnake" function or rename the object key from  `pointerEvents => "pointer-events"` in `.../internal/style.ts`

```html
<input name="name" style="position:absolute;width:25px;height:25px;opacity:0;margin:0px;pointerEvents:none;transform:translateX(-100%);">
```
### Files
- `src/lib/components/form-control.svelte`
- `src/lib/internal/style.ts`

**Comment by huntabyte** [comment]
The input definitely should not be receiving focus or pointer events, you're right about that one. It should be hidden completely from the user as the other component being used as the control should receive focus.

**Comment by wesharper** [comment]
It seems to me that a simple fix would be to just add `type="hidden"` to the generated input.
