### ISSUE TITLE
feature: add support for Superforms v2

### ISSUE THREAD

**Issue by arshia-gh** [huntabyte/formsnap#115]
Are there any plans to add support for Superforms v2

**Comment by huntabyte** [comment]
Yes, once it's no longer in alpha.

**Comment by callmeberzerker** [comment]
Can't wait for this, finally file upload properly solved. 🚀

**Comment by pheuter** [comment]
Will this come with support for adapters, so users who choose a different validation library, like arktype for example, will be able to use Formsnap as well? Or will Formsnap always force the `schema` property to be a Zod schema?

**Comment by huntabyte** [comment]
Yes @pheuter, the goal is to support exactly the same as Superforms does.

**Comment by callmeberzerker** [comment]
Lets go boys! https://www.reddit.com/r/sveltejs/comments/1aoc7q2/superforms_2_has_been_released/
