### ISSUE TITLE
Ability to handle recursive types

### ISSUE THREAD

**Issue by noobmaster19** [huntabyte/formsnap#119]
I have a entity that has a recursive structure.
```
Type instantiation is excessively deep and possibly infinite.ts(2589)
```

Is there anyway i can fix this?

**Comment by noobmaster19** [comment]
Hey, I'm still facing the same issue, is there some materials i can reference on how to set up a recursive type form?

**Comment by noobmaster19** [comment]
Hey! I'm actually still facing this issue, is this not supported?

**Comment by huntabyte** [comment]
You provided almost near 0 information with the issue. Regardless, we use types from sveltekit-superforms so if it is supported there it should be supported with formsnap. If not, try opening an issue there.
