### ISSUE TITLE
Adopt superforms 2.0.0 changes

### ISSUE THREAD

**Issue by MrExplode** [huntabyte/formsnap#134]
superforms [v.2.0.0](https://github.com/ciscoheat/sveltekit-superforms/releases/tag/v2.0.0) has been released with numerous bigger changes. It would be nice to have these changes adapted.

**Comment by HubbeDev** [comment]
@MrExplode Its already in progress. @huntabyte is working on it. [superforms-v2 branch](https://github.com/huntabyte/formsnap/tree/superforms-v2)

**Comment by MrExplode** [comment]
oh thanks

**Comment by huntabyte** [comment]
Duplicate of #115 . Please search existing issues before creating a new one.
