### ISSUE TITLE
[v0.5.0] <Input type="number" /> binds string value

### ISSUE THREAD

**Issue by pheuter** [huntabyte/formsnap#139]
### Describe the bug

Passing `[type="number"]` to a shadcn input does't appear to cast the value to a number.

### Reproduction

On latest shadcn-svelte, superforms, and formsnap:

```svelte
<script lang="ts">
  import { superForm } from 'sveltekit-superforms';
  import * as Form from '$lib/components/ui/form';
  import { Input } from '$lib/components/ui/input';

  const form = superForm(data.form, {
	onError: 'apply',
	dataType: 'json',
	async onSubmit({ formData }) {
		const token = await window.grecaptcha?.execute(PUBLIC_RECAPTCHA_KEY, { action: 'submit' });
		formData.set('token', token);
	}
});
  const { form: formData, enhance } = form;
</script>

<Form.Field {form} name="ownerSalary">
	<Form.Control let:attrs>
		<Form.Label>Annual Salary</Form.Label>
		<Input {...attrs} type="number" min={0} step={0.01} bind:value={$formData.ownerSalary} />
	</Form.Control>
	<Form.FieldErrors />
</Form.Field>
```

**input.svelte**

```svelte
<script lang="ts">
	import type { HTMLInputAttributes } from 'svelte/elements';
	import { cn } from '$lib/utils';
	import type { InputEvents } from '.';

	type $$Props = HTMLInputAttributes;
	type $$Events = InputEvents;

	let className: $$Props['class'] = undefined;
	export let value: $$Props['value'] = undefined;
	export { className as class };
</script>

<input
	class={cn(
		'flex h-10 w-full rounded-md border border-input bg-background px-3 py-2 text-base ring-offset-background file:border-0 file:bg-transparent file:text-sm file:font-medium placeholder:text-muted-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50 sm:text-sm',
		className
	)}
	bind:value
	on:blur
	on:change
	on:click
	on:focus
	on:focusin
	on:focusout
	on:keydown
	on:keypress
	on:keyup
	on:mouseover
	on:mouseenter
	on:mouseleave
	on:paste
	on:input
	{...$$restProps}
/>
```

**schema**

```ts
ownerSalary: z.number({ coerce: true }).min(0),
```

### System Info

```bash
System:
    OS: macOS 14.3.1
    CPU: (16) arm64 Apple M3 Max
    Memory: 4.73 GB / 48.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.19.1 - ~/.nvm/versions/node/v18.19.1/bin/node
    npm: 10.2.4 - ~/.nvm/versions/node/v18.19.1/bin/npm
    bun: 1.0.28 - ~/.bun/bin/bun
  Browsers:
    Chrome: 121.0.6167.184
    Safari: 17.3.1
  npmPackages:
    @sveltejs/kit: ^2.0.0 => 2.5.0 
    formsnap: ^0.5.0 => 0.5.0 
    svelte: ^4.2.0 => 4.2.11 
    sveltekit-superforms: ^2.4.0 => 2.4.0 
    zod: ^3.22.4 => 3.22.4
```

### Severity

blocking an upgrade

**Comment by shyakadavis** [comment]
Hi;

I might be wrong, but could this be related to these:

- https://github.com/sveltejs/svelte/issues/10256
> This is a limitation of the more static runtime in Svelte 4 and [will work as expected in Svelte 5](https://svelte-5-preview.vercel.app/#H4sIAAAAAAAACkWNzQqDMBCEX2VZBC2I3lMV-hxND_6sENA1mI1YQt69GCjeZr4ZZgLOZiGH6h2Q-5VQ4ctaLFG-9jLuoEUIS3Sb38eLNG7cjZVOs5aFBI5-8QQtZE56oeLx_AfnDQNccwpy9utAew4x1VhLZthZGqVIMxdt6vuAG8PWC4Sqqs4Ig-FJpWKrMSQRNULdacYS120ys6EJleye4if-ACQ34PjcAAAA)

- Workaround? https://github.com/huntabyte/shadcn-svelte/issues/574

**Comment by huntabyte** [comment]
@shyakadavis would be correct on this one.

Unfortunately, you can't expose the `type` prop when the `value` is being bound. You'd have to create separate input components for each `type`. The workaround provided is what I've determined to be the best solution atm.

**Comment by pheuter** [comment]
I guess the part I found confusing is that this worked in Formsnap 0.4.0

**Comment by huntabyte** [comment]
Ah, I see!

We were using change handlers and such under the hood to modify the value vs binding, which is why you couldn't bind to the value of the input which appeared to be a worse problem for people.

Coercion at the schema level is the best bet at the moment, or you could create a separate `NumberInput` component with the type hard-coded as `"number"` which would address the issue:
https://svelte.dev/repl/86b3859386dc4044a4c2d06e18f21ca8?version=4.2.11
