### ISSUE TITLE
contentlayer

### ISSUE THREAD

**Issue by xmlking** [huntabyte/formsnap#25]
would be nice if you can share how you are setup contentlayer with sveltekit projects :)
don't see instructions on their [site](https://contentlayer.dev/docs/environments/svelte-efe6735d)

**Comment by huntabyte** [comment]
Hey there @xmlking, reference this PR here: https://github.com/huntabyte/bits-ui/pull/78.

I didn't implement it, @multiplehats did, I just copied it from that project over to this one.
