### ISSUE TITLE
VSCode brought to halt after installing Forms

### ISSUE THREAD

**Issue by saturnonearth** [huntabyte/formsnap#28]
### Current Behavior

Upon installing the new Forms component, my VSCode started crashing was unable to perform even simple tasks.

I believe this may have something to do with the svelte-language-server and the large type definitions generated by ZOD and Superforms (but this is just a guess).

Is anyone else experiencing similar issues?

### Expected Behavior

The ability to use the Forms components without tears of sorrow.

### Steps To Reproduce

Install forms component, import and use.

**Comment by saturnonearth** [comment]
> Would you mind dropping the specs of your device so I can jump on a comparable one to test it out?

2021 Macbook Pro 14 inch M1 Pro, 16GB Memory

**Comment by tmadge** [comment]
Oh, actually, the same thing might have happened to me too. VSCode started chugging when it was trying to format my files on save. At the time I just chalked it up to Windows needing a reboot, but it was right around the time I started playing with shadcn-svelte & the forms.

A reboot seems to have fixed it and it hasn't happened since.

**Comment by huntabyte** [comment]
Interesting! I will try to investigate a bit this evening to see if I can determine the issue!

**Comment by saturnonearth** [comment]
> Interesting! I will try to investigate a bit this evening to see if I can determine the issue!

Could this be it? It's coming from form.svelte.d.ts

<img width="1212" alt="CleanShot 2023-09-07 at 18 47 34@2x" src="https://github.com/huntabyte/formsnap/assets/12503538/71fd631a-aa2f-4622-8e72-8690e187926d">

**Comment by huntabyte** [comment]
I'm curious if the same sized type is exported from Superforms when using it in isolation 🤔

**Comment by huntabyte** [comment]
Can confirm it is definitely not that large, so likely something idiotic I'm doing on my end. Will take a closer look at this now! @saturnonearth

**Comment by huntabyte** [comment]
Good news @saturnonearth, fixed that massive type generation, and there will be a release that fixes it inbound very soon! Thanks again for raising the issue
