### ISSUE TITLE
Unable to pass `delayed` to children components

### ISSUE THREAD

**Issue by saturnonearth** [huntabyte/formsnap#34]
Trying to access `delayed` in a child component. I have tried passing as prop, and I get an error stating it's not a store, and when using `getForm` it is undefined.

I am trying to use the Store within the `script` of the child component, and not just in the HTML, so the state matters upon init.

**Comment by huntabyte** [comment]
Hey @saturnonearth, thanks for raising this issue, opening a PR, and publishing a new release now that will fix this for you.
