### ISSUE TITLE
Formsnap Options Type not working

### ISSUE THREAD

**Issue by saturnonearth** [huntabyte/formsnap#42]
I am getting a TS red squiggly and..

`Generic type 'FormOptions' requires between 1 and 2 type arguments.ts(2707)`
 
when trying to declare an `options` var to be used for the `form.root` - even when almost nothing in it.

TS complains even with this:

```js
	import type { FormOptions } from 'formsnap';

	const options: FormOptions = {
		id: 'test'
	};
```

**Comment by huntabyte** [comment]
You'll want to pass the schema type as a generic argument to the options, will update the docs to reflect that!

```ts
const options: FormOptions<typeof myschema> = {
// ...
}
```
