### ISSUE TITLE
styling?

### ISSUE THREAD

**Issue by Schmell** [huntabyte/formsnap#44]
Maybe I missed something somewhere, but how do i style this stuff?

Update: i can style the 'stuff'. i guess i thought i could make generic styles for the form components.

**Comment by huntabyte** [comment]
How about if I add `data-` attributes to the different pieces so they can be styled using selectors across the entire app, would this address your issue? If not, what did you have in mind?

**Comment by Schmell** [comment]
The `data-` attribute would work. It is probably the simplest approach.
Will this still work with the `cn()` function?

A nice approach would be to just have the formsnap components (like shadcn-svelte) to mess with instead of building  component's on components inception

I tried to use your shadcn-svelte version, but `shadcn init` completely destroys my current style system. Maybe i will try that on my next project

**Comment by huntabyte** [comment]
It would work with the `cn` function if you were to pass tailwind classes to the form components!

**Comment by Schmell** [comment]
Cool man. Thanks
