### ISSUE TITLE
Memory leak with email validation in zod forms 

### ISSUE THREAD

**Issue by callmeberzerker** [huntabyte/formsnap#46]
### Current Behavior

The browser tab hangs and crashes

### Expected Behavior

Email validation works 

### Steps To Reproduce

1. basically start writing in the email field with characters and browser tab will grind to a halt (enter at least 50 characters)

### Link to Reproduction / Stackblitz

https://stackblitz.com/edit/github-zxmrcw?file=src%2Froutes%2F%2Bpage.svelte,src%2Froutes%2F%2Blayout.svelte

### More Information

I did some testing and this _only_ happens when validating the _email_ constraint -> and I have no running hypothesis why is that the case.

**Comment by huntabyte** [comment]
Wow, this is definitely a weird one, especially considering it only occurs when validating the email constraint 🤔.

Does this happen when using Superforms by itself, or only when using it with Formsnap? If it was happening for all the validation cases then it would make more sense, but the fact that it's only happening for this one is peculiar.

**Comment by huntabyte** [comment]
There's this issue here that might be related: https://github.com/colinhacks/zod/issues/2580

**Comment by huntabyte** [comment]
Going to close this as it isn't an issue with Formsnap itself, but rather an issue with Zod and complex email addresses.

As a solution in the meantime, you can stop using `.email()` and instead create your own custom one which someone recommended in another Zod issue regarding this:

```ts
const schema = z.object({
	email: z.regex(/^[a-zA-Z0-9.!#$%&’*+/=?^_`{|}~-]+@[a-zA-Z0-9-]+(?:\.[a-zA-Z0-9-]+)*$/)
})

**Comment by callmeberzerker** [comment]
Thank you so much! So weird that this is yet to be actionable by `zod`. 😄
