### ISSUE TITLE
How to integrate the sveltekit-flash-message when using codesnap?

### ISSUE THREAD

**Issue by callmeberzerker** [huntabyte/formsnap#51]
Hi there!

Thanks for these useful wrappers that make `superforms` joy to work with. I see there are open issues about exposing all the `superforms` stores (like [this one](https://github.com/huntabyte/formsnap/issues/43)). 

But what I am trying to do is integrate with [https://superforms.rocks/flash-messages](https://superforms.rocks/flash-messages) and there seems not be an easy way to achieve this right?

**Comment by huntabyte** [comment]
You should be able to accomplish this using the `options` prop that you can pass into the `Form.Root`, what isn't working?
