### ISSUE TITLE
How to use the Sveltekit snapshot mechanism from within the Form.Root context?

### ISSUE THREAD

**Issue by bfovez** [huntabyte/formsnap#54]
This library is a really great job! I'm in the process of integrating it in all my forms.

With sveltekit-superforms, I was used to do something like this to install the Sveltekit snapshot mechanism:

```typescript
const { capture, restore } = superForm(data.form, {...})
export const snapshot = { capture, restore }
```

But with formsnap, the capture & restore functions are available as properties of `Form.Root`, or as a result of the `getForm` function which be only be called within the context of `Form.Root`.

So the question is: how I can lift the capture & restore functions up to the script part of my page to `export const snapshot = { capture, restore }`?

Thank in advance for any advice!

**Comment by bfovez** [comment]
I tried this `Snap.svelte` component:
```svelte
<script lang="ts">
	import { getForm } from 'formsnap'
	export const { capture, restore } = getForm()
</script>
``` 

which I placed in tge `Form.Root`:
```svelte
<script lang="ts">
	import Snap from './Snap.svelte'
	.....

	export let data: PageData
	let capture: any
	let restore: any

	// Let's see it in action in the browser console
	export const snapshot: Snapshot = {
		capture: () => {
			const res = capture()
			console.log('Capturing', res)
			return res
		},
		restore: (snapshot) => {
			console.log('Restoring', snapshot)
			restore(snapshot)
		}
	}
</script>

<Form.Root
	form={data.form}
	{options}
	let:config
	...
>
	<Snap bind:capture bind:restore />

	<Form.Field {config} name="title" let:attrs>
		{attrs.input.value} // <--- Correctly restored
	</Form.Field>

	<Form.Field {config} name="title">
		<Form.Input /> // <--- NOT restored
	</Form.Field>

	...
</Form.Root>
```

The `capture` and `restore` methods do a could job, as I can check in the console, but the `<Form.Input />` are not properly restored, although the `attrs` is.

**Comment by huntabyte** [comment]
With the latest `formsnap` update, are you stlll able to reproduce this?

**Comment by huntabyte** [comment]
Closed by #83 which will solve this problem if not fixed by the previous releases.

**Comment by bfovez** [comment]
Hi Hunter,
No, it works fine with the latest update. Thank you!
And yes, #83 <https://github.com/huntabyte/formsnap/pull/83> will solve
many issues I think.

Le mer. 1 nov. 2023 à 16:16, Hunter Johnston ***@***.***> a
écrit :

**Comment by juanpujol** [comment]
Hi. Today I tried to do this like instructed in Superforms

This works (+page.svelte)

```ts
const { data } = $props()
const { form, errors, constraints, enhance, delayed, capture, restore } = superForm(data.form)
export const snapshot = { capture, restore }
```

But it doesn't work when I do it in the form.svelte example (shadcn)

This doesn't work (form.svelte)

```ts
const form = superForm(data, {validators: zodClient(signInFormSchema)})
const { form: formData, errors, constraints, enhance, delayed, capture, restore } = form
export const snapshot = { capture, restore }
```

Not sure what I'm missing. Is there any docs for this?

@bfovez how did you make it work?

Also, thank you @huntabyte great job!

**Comment by bfovez** [comment]
Hi Juan,

I did make it work just as you did yourself :

const form = superForm(data, {
   validators: zodClient(...),
   resetForm: false,
   taintedMessage: null,
   dataType: 'json',}
)
const { form: formData, ..., capture, restore } = form
export const snapshot = { capture, restore }


Le sam. 22 juin 2024 à 20:33, Juan Pujol ***@***.***> a écrit
:
>
> Hi. Today I tried to do this like instructed in Superforms
>
> This works (+page.svelte)
>
> const { data } = $props()
> const { form, errors, constraints, enhance, delayed, capture, restore } =
superForm(data.form)
> export const snapshot = { capture, restore }
>
> But it doesn't work when I do it in the form.svelte example (shadcn)
>
> This doesn't work (form.svelte)
>
> const form = superForm(data, {validators: zodClient(signInFormSchema)})
> const { form: formData, errors, constraints, enhance, delayed, capture,
restore } = form
