### ISSUE TITLE
Allocated space for validation taking up spacing in DOM

### ISSUE THREAD

**Issue by saturnonearth** [huntabyte/formsnap#56]
The  `p` tag that is researved for showing validation text should the input be invalid or required, is taking space up in the dom as shown here.

I could see this being intentional if if the height of the `p` tag was the same as the `font-height`, as to not shift the DOM if an error occurs, but seeing as it's already so small, I assume this was just a mistake.

Should the `p` tag have a class of `hidden` when not visible?

Here is an example of how it is now:

![CleanShot 2023-10-01 at 01 52 40@2x](https://github.com/huntabyte/formsnap/assets/12503538/5042be4e-f155-4efa-9de0-4d672ce5f8d3)

**Comment by huntabyte** [comment]
> I could see this being intentional if if the height of the `p` tag was the same as the `font-height`, as to not shift the DOM if an error occurs, but seeing as it's already so small, I assume this was just a mistake.

This is the exact purpose I chose not to apply any specific styles to it, it's headless so you have the freedom to compose it into however you best see fit for your project, whether that's applying the `hidden` if no errors are there, which could be done using the `getFormField()` inside of a wrapper of the `Form.Validation` primitive, or however else you'd see fit!
