### ISSUE TITLE
Issue in ActionResult type of result in OnResult method

### ISSUE THREAD

**Issue by ma13gagan** [huntabyte/formsnap#57]
Hey there,

I am facing an issue with `onResult` method of `FormOptions`.

ActionResult type does not give any autocompletion on the `result.type` property. The `type` property is just typed as `any` instead of `"success" | "redirect" | "error" | "failure"`

![image](https://github.com/huntabyte/formsnap/assets/65103311/77bdd97c-ad61-4893-84c1-b29b189d082e)

![image](https://github.com/huntabyte/formsnap/assets/65103311/2bb3ac38-872d-47b8-8465-11aa3073c16f)

**Comment by huntabyte** [comment]
Thanks for raising this issue! Will look into it!

**Comment by huntabyte** [comment]
Are you still experiencing this issue with the latest update? @ma13gagan

**Comment by huntabyte** [comment]
Closed by #83
