### ISSUE TITLE
[Feature Request] Add utility function `getFormSchema()`

### ISSUE THREAD

**Issue by BenocxX** [huntabyte/formsnap#61]
It would be useful to add the Zod Schema used by the form (the one that ends up in the "config" object returned by the Form.Root slot) to the context api.

I currently use this simple component to accomplish this:
```html
<!-- form-schema.svelte -->
<script lang="ts">
  import { setSchema } from '$lib/utils/zod-utils';
  import z from 'zod';

  export let schema: z.ZodEffects<any> | z.ZodObject<any>;

  setSchema(schema); // Sets the schema using setContext();
</script>

<slot />
```

My main use case is to access the schema inside the Label component to display a `*` if the field is required. To do so, I need to have access to the zod schema. Form.Label component:
```html
<!-- form-label.svelte -->
<script lang="ts">
  import type { Label as LabelPrimitive } from 'bits-ui';
  import { getFormField } from 'formsnap';

  import { Label } from '$lib/components/ui/label';
  import { getSchema, isRequired } from '$lib/utils/zod-utils';

  type $$Props = LabelPrimitive.Props;

  let className: $$Props['class'] = undefined;
  export { className as class };

  const { ids, name } = getFormField();
  const schema = getSchema();
</script>

<Label for={ids.input} class={className} {...$$restProps}>
  <slot />
  {#if schema && isRequired(name, schema)}
    <span class="text-destructive">*</span>
  {/if}
</Label>
```

I could pass the schema to the Label component as a props, but I feel like it's not a long term solution. 

The schema should be accessible like `getForm()` and `getFormField()`.

I feel like other people will be needing this in the future. There are currently no way to get the "config" except from `Form.Root`'s slot.

**Comment by pekeler** [comment]
Was this utility function removed again? I can't find it anywhere in 1.0.0.

**Comment by BenocxX** [comment]
> Was this utility function removed again? I can't find it anywhere in 1.0.0. (I have the same use case - wanting to change the label if the field is required.)

I haven't use Formsnap since 1.0. The feature was never documented so you won't find it in the docs. That being said, you should be able to import the function "getFormSchema()". Though, it may have been removed for 1.0...
