### ISSUE TITLE
dataType: "json" not working in v0.3.0

### ISSUE THREAD

**Issue by fr0stf0x** [huntabyte/formsnap#79]
here is my configuration

```svelte
<Form.Root
  method="POST"
  options={{
    onUpdated,
    dataType: 'json',
    warnings: {
      duplicateId: false,
    },
  }}
  form={data.form}
  schema={ruleSchema}
  let:submitting
>
```

I got the message 

`error happened: Object found in form field "rateLimitConfig". Set the dataType option to "json" and add use:enhance to use nested data structures. More information: https://superforms.rocks/concepts/nested-data {}
pageStatus: 500
pageError: {
  message: "Whoops!",
  code: "UNKNOWN"
}
`

Had to revert to v0.2.1

**Comment by fr0stf0x** [comment]
here is schema config

```ts
const rateLimitConfigSchema: z.ZodType<RateLimitConfig> = baseRateLimitConfigSchema
  .extend({
    and: z.lazy(() => z.array(rateLimitConfigSchema)).optional(),
  })
  .refine(
    ({ and, when }) => {
      const isValid = (!isEmpty(and) && isEmpty(when)) || (isEmpty(and) && !isEmpty(when));

      return isValid;
    },
    {
      message: 'Rate limit or condition(s) must be defined',
    },
  );

const ruleSchema = z.object({
  id: z.string().optional(),
  prefixId: z.string().optional(),
  totalDescendants: z.number().optional(),
  name: nameSchema,
  description: descriptionSchema.optional(),
  rateLimitConfig: rateLimitConfigSchema.default({
    header: {
      key: '',
    },
  }),
});

```

**Comment by huntabyte** [comment]
Hey there! it seems like a fix for other issues may have introduced this one, which is exactly why I want to invest some resources into #77.

Are you using formsnap components, headless with actions, handlers, or what specifically?

If you could provide a minimal repro repo that would be fantastic and allow me to solve this much faster!

**Comment by bfovez** [comment]
Here is a [minimal repro repo](https://github.com/bfovez/formsnap-minimal)

**Comment by huntabyte** [comment]
Just noticed your repro isn't using the `dataType` json! @bfovez

**Comment by huntabyte** [comment]
About to release a patch that should fix this issue! Oversight on my end so I apologize!

**Comment by bfovez** [comment]
It seems that m'y minimal repo was top minimal! 😀

Le mar. 31 oct. 2023, 19:39, Hunter Johnston ***@***.***> a
écrit :
