### ISSUE TITLE
Styling via data attributes has broken

### ISSUE THREAD

**Issue by pevey** [huntabyte/formsnap#93]
I recently updated a project from formsnap 0.2.0 to latest on npm as of today.  Styling via the data-fs labels no longer worked.  (https://www.formsnap.dev/docs/styling)  Reverting to version 0.2.0 resolved the issue.

**Comment by bje259** [comment]
It looks like data-fs-select is applied in "form-input.svelte", "form-radio.svelte", "form-select.svelte" (this one makes sense) and "form-textarea.svelte"  I was successfully able to apply styles to my input boxes using the data-fs-select data attribute, but I doubt that is intended :)
