### ISSUE TITLE
Submitting form without submit button

### ISSUE THREAD

**Issue by noobmaster19** [huntabyte/formsnap#94]
Have a usecase similar to this:

https://stackoverflow.com/questions/77306898/how-to-submit-a-form-in-sveltekit-without-a-button

But I don't seem to be able to find any resources on how to get a reference to the actual form below, any idea how this might work?

**Comment by huntabyte** [comment]
In this situation, it's probably best to check out this part of the docs: https://www.formsnap.dev/docs/headless-usage

More specifically the part about Native form elements, which will let you access the form the way you want!
