### ISSUE TITLE
Expected object, received promise

### ISSUE THREAD

**Issue by JustDenP** [huntabyte/formsnap#99]
@huntabyte After upgrading to sveltekit v2 and superforms 13.1, all forms on my site stopped working. 
Zod error: ```Expected object, received promise```. 

I also took the default form from https://www.shadcn-svelte.com/docs/components/form in case the problem is only with my forms, but the same error happened with the example form.

I hope the problem can be fixed soon 🤞 Thank you

**Comment by huntabyte** [comment]
You need to await the return from the form.

**Comment by JustDenP** [comment]
Thank you!
